name: blue_thermal_helper
description: "Reusable Flutter helper for Bluetooth thermal printer (ESC/POS)"
version: 1.0.7
homepage: https://github.com/henrywijayalie/blue_thermal_helper
repository: https://github.com/henrywijayalie/blue_thermal_helper
issue_tracker: https://github.com/henrywijayalie/blue_thermal_helper/issues

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  print_bluetooth_thermal: ^1.1.9
  esc_pos_utils_plus: ^2.0.4
  image: ^4.7.2
  intl: ^0.20.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.rywtech.blue_thermal_helper
        pluginClass: BlueThermalHelperPlugin
      ios:
        pluginClass: BlueThermalHelperPlugin
